#!/usr/bin/env bash
# pandora_install_listener_schedule.sh — one-time installer for the school-hours
# listener schedule on Pandora.
#
# Installs a systemd timer that enforces the listener window:
#   Mon–Fri 06:00  → systemctl start final-face-listeners.service
#   Mon–Fri 17:00  → systemctl stop  final-face-listeners.service
#
# The enforce script is state-based (start-or-stop depending on current time),
# and the timer also fires ~2 min after boot, so a reboot at any hour converges
# to the correct state — no drift from missed cron edges.
#
# NOTE: this service handles MORNING ATTENDANCE as well as afternoon pickup,
# which is why the window opens at 06:00 (late cutoff is 07:30; kids scan
# from ~06:00), not at pickup time.
#
# Usage (as root):
#   sudo bash backend/scripts/pandora_install_listener_schedule.sh
#
# Optional overrides (env vars):
#   SERVICE_NAME=final-face-listeners.service
#   WINDOW_START=06:00      # HH:MM, 24h
#   WINDOW_END=17:00        # HH:MM, 24h
#   DAYS=Mon..Fri           # systemd OnCalendar day spec
set -Eeuo pipefail

SERVICE_NAME="${SERVICE_NAME:-final-face-listeners.service}"
WINDOW_START="${WINDOW_START:-06:00}"
WINDOW_END="${WINDOW_END:-17:00}"
DAYS="${DAYS:-Mon..Fri}"

ENFORCE_SCRIPT=/usr/local/sbin/final-face-listener-schedule
UNIT_SERVICE=/etc/systemd/system/final-face-listener-schedule.service
UNIT_TIMER=/etc/systemd/system/final-face-listener-schedule.timer

log() { printf '[%s] %s\n' "$(date --iso-8601=seconds)" "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }

[[ "$(id -u)" -eq 0 ]] || die "run as root:  sudo bash $0"
systemctl cat "$SERVICE_NAME" >/dev/null 2>&1 || die "service '$SERVICE_NAME' not found"

hhmm_to_min() { local h m; IFS=: read -r h m <<< "$1"; echo $((10#$h * 60 + 10#$m)); }
START_MIN=$(hhmm_to_min "$WINDOW_START")
END_MIN=$(hhmm_to_min "$WINDOW_END")
[[ "$START_MIN" -lt "$END_MIN" ]] || die "WINDOW_START must be before WINDOW_END"

log "Writing $ENFORCE_SCRIPT"
cat > "$ENFORCE_SCRIPT" <<EOF
#!/usr/bin/env bash
# Auto-generated by pandora_install_listener_schedule.sh — do not edit by hand.
# Starts or stops $SERVICE_NAME based on the school-hours window
# ($DAYS $WINDOW_START-$WINDOW_END).
set -Eeuo pipefail
SERVICE=$SERVICE_NAME
START_MIN=$START_MIN
END_MIN=$END_MIN

dow=\$(date +%u)   # 1=Mon … 7=Sun
now_min=\$(( 10#\$(date +%H) * 60 + 10#\$(date +%M) ))

in_window=no
if (( dow <= 5 && now_min >= START_MIN && now_min < END_MIN )); then
  in_window=yes
fi

if [[ "\$in_window" == yes ]]; then
  if ! systemctl is-active --quiet "\$SERVICE"; then
    echo "In window (\$(date +%H:%M), day \$dow) — starting \$SERVICE"
    systemctl start "\$SERVICE"
  fi
else
  if systemctl is-active --quiet "\$SERVICE"; then
    echo "Outside window (\$(date +%H:%M), day \$dow) — stopping \$SERVICE"
    systemctl stop "\$SERVICE"
  fi
fi
EOF
chmod 755 "$ENFORCE_SCRIPT"

log "Writing $UNIT_SERVICE"
cat > "$UNIT_SERVICE" <<EOF
[Unit]
Description=Enforce school-hours window for $SERVICE_NAME

[Service]
Type=oneshot
ExecStart=$ENFORCE_SCRIPT
EOF

log "Writing $UNIT_TIMER"
cat > "$UNIT_TIMER" <<EOF
[Unit]
Description=School-hours schedule for $SERVICE_NAME ($DAYS $WINDOW_START-$WINDOW_END)

[Timer]
# Boundary edges (start + stop) …
OnCalendar=$DAYS $WINDOW_START
OnCalendar=$DAYS $WINDOW_END
# … a periodic sweep so drift self-corrects (e.g. auto-update's
# 'systemctl restart' starting the service after an evening push) …
OnCalendar=*-*-* *:00/30
# … plus shortly after every boot, so a reboot at any hour converges.
OnBootSec=2min
Persistent=true
Unit=final-face-listener-schedule.service

[Install]
WantedBy=timers.target
EOF

systemctl daemon-reload
systemctl enable --now final-face-listener-schedule.timer

log "Running the enforce script once now to converge to the correct state"
"$ENFORCE_SCRIPT" || true

log "Done. Timer status:"
systemctl list-timers final-face-listener-schedule.timer --no-pager || true
log "To uninstall: systemctl disable --now final-face-listener-schedule.timer && rm -f $UNIT_TIMER $UNIT_SERVICE $ENFORCE_SCRIPT && systemctl daemon-reload"
